# Generated by Django 3.2 on 2024-02-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('img_url', models.CharField(max_length=255, verbose_name='图片地址')),
                ('content', models.TextField(max_length=255, verbose_name='公告内容')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('section', models.CharField(max_length=255, verbose_name='部分内容')),
                ('content', models.TextField(verbose_name='内容')),
                ('img_url', models.CharField(max_length=255, verbose_name='图片链接')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('text', models.TextField(default='', verbose_name='短信内容')),
                ('lable', models.IntegerField(default=0, verbose_name='分类标签')),
                ('type', models.CharField(max_length=255, verbose_name='已读类型')),
                ('date', models.CharField(default='暂无', max_length=255, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='Popularization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('img_url', models.CharField(max_length=255, verbose_name='图片地址')),
                ('content', models.TextField(verbose_name='知识科普内容')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
            ],
        ),
    ]
